Revert "Exclude `XCBuildSupport` when building with CMake (#7358)" (#7371)
This reverts commit 52870620e7b550b492086ae877d6eb9afd94c33f, which
causes macOS toolchain builds to fail with:
```
main/main.swift:345: Fatal error: SwiftPM was built without XCBuild support
```

Also adds the DriverSupport dependency to XCBuildSupport, which was
skipped in #7258 because #7358 was merged (but we're reverting that).