Binary dependencies of C/C++ modules break build planning (#8056)
Fix a regression where the build planning phase will early terminate if
SwiftPM packages contain binary targets that C/C++ products refer to,
https://github.com/swiftlang/swift-package-manager/issues/8055.

### Motivation:

When running `swift build` on SwiftPM packages with binary targets that
C++ products refer to, they will early terminate during the build
planning phase with the following error:

```swift
error: InternalError(description: "Internal error. Please file a bug at https://github.com/swiftlang/swift-package-manager/issues with this info. unknown module: <ResolvedModule: Python, binary>")
```

### Modifications:

Remove the guard, so we do not fail ~~if the module dependency does not
yet exist in the build plan's target map, which I think is normal~~ on
binary targets that C++ products refer to, since they don't have build
descriptions.

### Result:

When running `swift build` on SwiftPM packages with binary targets that
C++ products refer to, the build planning phase will proceed
successfully without error.

---------

Signed-off-by: furby™ <devs@wabi.foundation>