Rewrite PackageCollectionsSigning using swift-certificates (#6468)
* Rewrite PackageCollectionsSigning using swift-certificates

Motivation:
`PackageCollectionsSigning` was written before `swift-certificates` and `swift-asn1` were available. The implementation relied on BoringSSL C library via `CCryptoBoringSSL`, which is not meant to be used outside of `swift-crypto` because it introduces Swift-breaking changes often (as SwiftPM had experienced with version `2.4.1`).

Modifications:
- Rewrite `PackageCollectionsSigning` using `swift-certificates` and `swift-asn1` so we can remove `CCryptoBoringSSL` dependency.
- `PackageCollectionsSigningLibC`, which contains SwiftPM's implementation of OCSP, is no longer needed and removed in this PR.

* Fix file not found error in tests

* Fix compilation error: cannot find 'Task' in scope

* Specify RSA signing padding to ensure backwards compatibility