[test] Update PD5LoadingTests.swift for a parser fix that suppressed a diagnostic it was checking for.
The test parses the code below and checks for a "expected ')' in expression
list" diagnostic:

```
import PackageDescription

let package = Package(
    name: "Trivial",
    targets: [
        .target(
            name: "foo",
            dependencies: []),
)
```
Prior to the parser fix the invalid collection literal failed to parse but the
error status wasn't propagated up to the containing argument list parsing code,
so it produced an additional (and undesirable) missing right token diagnostic
that this test was checking for.

/tmp/t.swift:9:1: error: expected expression in container literal
)
^
/tmp/t.swift:9:2: error: expected ')' in expression list
)
 ^
/tmp/t.swift:2:22: note: to match this opening '('
let package = Package(
                     ^
Afer the parser fix in https://github.com/apple/swift/pull/30187, we only
report the first container literal error and suppress the rest:

/tmp/t.swift:9:1: error: expected expression in container literal
)
^