Show human-readable git errors (#8152)
Show human-readable git errors

### Motivation:

I noticed that when swiftpm cache is empty and there's a network issue,
then `swift build` throws an error which is not helpful, something like
this:

```
error: GitShellError(result: <AsyncProcessResult: exit: terminated(code: 128), output:
 
>)
```

where it does say "output" but doesn't actually include output or show
any details about what dependency caused the error.

### Modifications:

- `GitShellError` now conforms to CustomStringConvertible protocol, so
that when it is thrown then it will print what was the git error
- `GitShelError` has now package access to allow catching it explicitly.

### Result:

Errors now tell details of the failure: 

```
error: Git command 'git -C /Users/yy/Library/Caches/org.swift.swiftpm/repositories/postgres-kit-e4358808 config --get remote.origin.url' failed: fatal: cannot change to '/Users/yy/Library/Caches/org.swift.swiftpm/repositories/postgres-kit-e4358808': No such file or directory
```

---------

Co-authored-by: Max Desiatov <m_desiatov@apple.com>