Update BuildToolTests.testBuildCompleteMessage (#3498)
Motivation:
The build output on Linux has changed. Causing self hosted Linux test to fail ([example](https://ci.swift.org/job/swift-package-manager-self-hosted-Linux-smoke-test/2051/)):

```
21:29:49 Test Case 'BuildToolTests.testBuildCompleteMessage' started at 2021-05-13 04:29:06.495
21:29:49
/home/buildnode/jenkins/workspace/swift-package-manager-self-hosted-Linux-smoke-test/branch-main/swiftpm/Tests/CommandsTests/BuildToolTests.swift:256: error: BuildToolTests.testBuildCompleteMessage : XCTAssertTrue failed - [1/4] Compiling Bar Bar.swift
21:29:49 [3/6] Merging module Bar
21:29:49 [5/7] Wrapping AST for Bar for debugging
21:29:49 [6/9] Compiling Foo Foo.swift
21:29:49 [7/9] Compiling Foo main.swift
21:29:49 [9/11] Merging module Foo
21:29:49 [11/12] Wrapping AST for Foo for debugging
21:29:49 [12/12] Linking Foo
21:29:49 [12/12] Build complete!
21:29:49
21:29:49 Test Case 'BuildToolTests.testBuildCompleteMessage' failed (5.24 seconds)
```

Modification:
Update expected output in `BuildToolTests.testBuildCompleteMessage`.