Add missing kind values to TargetStartedInfo (#2849)
When I use:
`swift build --build-system xcode -v`
I get:
error: failed parsing XCBuild output: unexpected JSON message: : dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize Kind from invalid String value Package Product", underlyingError: nil))