Provide the downloadable metal toolchain to swiftbuild (#9434)
Provide the downloadable metal toolchain to swiftbuild using
EXTERNAL_TOOLCHAINS_DIR env variable

### Motivation:

https://github.com/swiftlang/swift-package-manager/issues/9202 [Parity]
error: unable to spawn process 'metal' (No such file or directory)

Requires CI to include Metal toolchain in order to enable Metal tests:
https://github.com/swiftlang/swift-package-manager/issues/9443