Fix `[FunctionalTests.CFamilyTargetTestCase testObjectiveCPackageWithTestTarget]` test case.
The issue was that the default value for the `publicHeadersPath` target
property is `include` but the include directory was named `Include`.

On case insenstive file systems this would work fine but it causes
the test to fail on case sensitive file systems.

A typical error message is

```
    warning: no include directory found for target 'ObjCmacOSPackage'; libraries cannot be imported without public headersCompile ObjCmacOSPackage HelloWorldExample.m
    Compile ObjCmacOSPackageTests HelloWorldTest.m
    /some_path/CFamilyTargets_ObjCmacOSPackage/Sources/HelloWorldExample.m:2:9: fatal error: 'HelloWorldExample.h' file not found
    #import "HelloWorldExample.h"
            ^~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```