Add more context for validation errors for target properties. (#8612)
Add more context for validation errors for target properties.

### Motivation:

I came across a post
https://forums.swift.org/t/getting-error-on-package-resolve/75419 which
reports the error message to be not clear. I thought I could clarify the
message.

```
error: 'xerr': target 'Penny' contains a value for disallowed property 'settings'
```

### Modifications:

I've updated the message for the error, so it includes more details to
narrow down what is the culprit:
 - highlight that the property depends on the target type
- show the value of the property, so that there's a hint what line in
the Package.swift lead to the error (for example, linkerSettings or
cxxSettings)

### Result:


Before:

```
error: 'xerr': target 'Penny' contains a value for disallowed property 'settings'
```

After:

```
error: 'xerr': target 'Penny' is assigned a property 'settings' which is not accepted for
the binary target type. The current value of the property has the following representation: 
[PackageModel.TargetBuildSettingDescription.Setting(
tool: PackageModel.TargetBuildSettingDescription.Tool.linker,
kind: PackageModel.TargetBuildSettingDescription.Kind.linkedFramework("AVFoundation"),
condition: nil)].
```