PackagePIFProjectBuilder+Modules.swift: Add missing `.emscripten`
```
14:09:47  /Users/ec2-user/jenkins/workspace/swift-package-manager-with-xcode-self-hosted-PR-osx-release-toolchain/branch-main/swiftpm/Sources/SwiftBuildSupport/PackagePIFProjectBuilder+Modules.swift:569:17: error: switch must be exhaustive
14:09:47  567 |             for platform in ProjectModel.BuildSettings.Platform.allCases {
14:09:47  568 |                 // darwin & freebsd
14:09:47  569 |                 switch platform {
14:09:47      |                 |- error: switch must be exhaustive
14:09:47      |                 `- note: add missing case: '.emscripten'
14:09:47  570 |                     case .macOS, .macCatalyst, .iOS, .watchOS, .tvOS, .xrOS, .driverKit, .freebsd:
14:09:47  571 |                         impartedSettings[.OTHER_LDFLAGS, platform] = ["-lc++", "$(inherited)"]
```