Improve error message when tools version is missing
A package that didn't have a tool-version specified at the top of the
manifest produced the following error:

```
error: 'toolsversion-identity': package 'package.swift' is using Swift
tools version 3.1.0 which is no longer supported; consider using '//
swift-tools-version: 6.4' to specify the current tools version
```

It misidentifies the package identitiy as being "package.swift" instead
of the actual name of the package.

This is reproducible by running `swift package dump-package` on a very
simple package, just a Package.swift in an otherwise empty folder that
looks like:

```
import PackageDescription

let package = Package(name: "ToolsVersionIdentity")
```

After this change, the error now contains the package's actual identity
instead of `package.swift`:

```
error: 'toolsversion-identity': package 'toolsversion-identity' is using
Swift tools version 3.1.0 which is no longer supported; consider using '//
swift-tools-version: 6.5' to specify the current tools version
```