[5.4] [Bootstrap] Do not pass `-Ddispatch_DIR` to the Yams CMake build (#3363) (#3423)
* [Bootstrap] Do not pass `-Ddispatch_DIR` to the Yams CMake build (#3363)

With the version-bump of Yams in https://github.com/apple/swift/pull/36366, Yams `4.0.2` now actually expresses the dependency on Dispatch in its CMake config.

With the current behavior of passing `-Ddispatch_DIR` to its CMake build, we have the following problem on Linux:
- `swift`'s `build-script` installs Dispatch into a just-built toolchain which we use to build SwiftPM, which will contain, among other things, the Dispatch `.swiftmodule`.
- The compiler workspace checkout of `swift-corelibs-libdispatch` also contains a copy of the Dispatch `.swiftmodule`.

Both of these will be found, leading to build failures like:
```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-nightly-install/usr/lib/swift/dispatch/module.modulemap:1:8: error: redefinition of module 'Dispatch'
19:37:47 module Dispatch {
19:37:47        ^
19:37:47 /home/buildnode/jenkins/workspace/swift-PR-Linux/branch-main/swift-corelibs-libdispatch/dispatch/module.modulemap:1:8: note: previously defined here
19:37:47 module Dispatch {
19:37:47        ^
19:37:47
```
We also cannot put off building `libDispatch` until SwiftPM is built, because the `libDispatch` dylib is required to link SwiftPM.
Not passing `-Ddispatch_DIR` to Yams' CMake build causes it to successfully locate the Dispatch package in the just-built toolchain on its own.

(cherry picked from commit 6af862d3a7efb3108334be0d3e3e33641c91f267)

* Fix invalid assumptions leading to unit test failures on Apple Silicon. (#3328)

rdar://75113176
(cherry picked from commit 3ff6f8bdd465f71a200e4e9a3ca52c37509dc9e3)

* Disable `testExplicitSwiftPackageBuild` on Apple Silicon because it relies on compiler fixes from later compiler versions, on this platform.

Co-authored-by: Artem Chikin <achikin@apple.com>
Co-authored-by: Anders Bertelrud <anders@apple.com>