Improve error handling for 'package-registry login' command (#6286)
* Improve error handling for 'package-registry login' command

Motivation:
When running `login` with `--netrc` and `--netrc-file` options and the custom netrc file doesn't exist, the command fails immediately with file not found error:

```
swift-package-registry --netrc --netrc-file ./netrc-test login
Error: Did not find netrc file at /Users/appleseed/netrc-test.
```

Which can be confusing.

Modifications:
Rearrange logic so that we initialize `AuthorizationProvider` first thing and display better error messages to user.

```
Error: credential store is invalid: did not find netrc file at /Users/appleseed/netrc-test
```