[SE-0509] Software Bill of Materials (SBOM) Generation in SwiftPM [Follow-Up 2] (#9803)
This is a second follow-up PR from review feedback on
https://github.com/swiftlang/swift-package-manager/pull/9766

### Motivation:

For the SBOM feature, some functions were added to
`SBOMGraphsConverter.swift` that extended `PackagePIFBuilder`. These
functions helped convert names between PIF targets and build targets.

In this PR, functions were moved to `PackagePIFBuilder+Helpers.swift`,
so that they aren't part of an extension in a different module, which is
confusing to a developer.

The functions were not moved in the original SBOM PRs due to a build
error in smoke tests on macOS and Windows:

```
Undefined symbols for architecture arm64:
  "protocol conformance descriptor for Swift.String : _StringProcessing.RegexComponent in RegexBuilder", referenced from:
      lazy protocol witness table accessor for type Swift.String and conformance Swift.String : _StringProcessing.RegexComponent in RegexBuilder in libSwiftBuildSupport.a[6](PackagePIFBuilder+Helpers.swift.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

This build error has been resolved by removing a `startsWith` function
call.

### Modifications:

- Moved functions from `SBOMGraphsConverter.swift` to
`PackagePIFBuilder+Helpers.swift` (consolidates functions in the same
extension and removes confusion)
- Changed `startsWith` function call to `first` function call (resolves
build error)

### Result:

This should not impact the functionality of the SBOM feature or any
other existing features.