Verify product dependencies w/ target platform, vs. hardcoded `macOS` (#6963)
Product dependencies are now verified using the `buildEnvironment`'s
platform, instead of the hardcoded `macOS` platform.

This builds on the work of #6732, now allowing cross-compilation of
product dependencies 🎉

### Motivation:
Let's say we're cross-compiling macOS -> iOS simulator, with a host
system of `macOS v13`.
```swift
let package = Package(
    name: "SwiftFlashlight",
    products: [.library(...)],
    platforms: [.iOS(.v16)],
    dependencies: [
        // internally, for iOS(.v16), macOS(.v14)
        .package(url: "probably/alamofire", exact: "1.2.3")
    ],
    // ...
)
```

As long as we set our triple & SDK, we _should_ be good... (and, with
#6828, only the triple needed)
```fish
> swift build --triple arm64-apple-ios-simulator \
              --sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)"
...
error: the library 'SwiftFlashlight' requires macos 10.13,
but depends on the product 'probably/alamofire' which requires macos 10.14;  [...]
```

Even though `SwiftFlashlight` only supports `iOS(.v16)`,
[SupportedPlatform](https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageDescription.md#supportedplatform)
"[by] default, [...] assigns a predefined minimum deployment version for
each supported platforms unless you configure supported platforms
[...]". As a side-effect, `macOS` is inferred as a valid platform. (This
is why no "target/platform mismatch" error was thrown.)

Previously, product dependencies were verified against `macOS`, rather
than the target platform. Since `macOS` is always inferred, this
surfaced as a "woah! your dependencies are out of sync".

```swift

let swiftFlashlight = Package(
    platforms: [
        .iOS(.v16),
        .macOS(.v13) // <-- inferred-|
    ],                               |
)                                    |-- // since --triple is .iOS,
                                     |   // shouldn't be comparing
let probably/alamofire = Package (   |   // macOS.
    platforms: [                     |
        iOS(.v16),                   |
        macOS(.v14)] // <-- inferred-|
    ]
)
```

Now, the intention of `--triple` is respected 🐱

### Modifications:
- `validateDeploymentVersionOfProductDependency` accepts a
`buildEnvironment` containing the target platform

### Result:

Product dependencies can now be compiled for `darwin` other than macOS
-- i.e, iOS :)

### Future work

- Target-level or product-level platform support is still up in the air
- This only applies to `triple.isDarwin()` -- perhaps a next step of
verifying dependencies against non-darwin?

---------

Co-authored-by: Max Desiatov <m_desiatov@apple.com>