Fix warning bug from previous commit description
- This commit fixes the warning described in the previous commit.
- Basically, instead of overlaying the generated umbrella header in the
  public headers directory, it is placed in a new directory within
  the build directory. The benefit here is that _a mixed target with a
  custom module map that includes an umbrella header_ will not cause a
  warning that the umbrella header does not include the generated
  umbrella header.
- Updated the tests the test this behavior.
- One weird issue that arose is the umbrella header does not work as
  expected when imported into a client. Despite being in the HSP and
  containing absolute paths to each public header, it will throw a weird
  error like such:

```
error: declaration of 'Driver' must be imported from module 'BasicMixedTarget' before it is required
@property(nullable) Driver *driver;
                    ^
/Users/nickcooke/Developer/swift-package-manager/Fixtures/MixedTargets/BasicMixedTargets/Sources/BasicMixedTarget/include/Driver.h:4:12: note: declaration here is not visible
@interface Driver : NSObject
```

- The next step is to figure out if I can exclude the generated
  umbrella's HSP when compiling individual clang files...

- ALTERNATIVE APPROACH: An alternative approach that might be better is
  to parse the custom module map and add `header $(ModuleName)/$(ModuleName).h`