Update to swift-crypto 2.4.1 (#6433)
Motivation:
swift-crypto 2.4.1 includes updates in BoringSSL that cause `Unsafe*Pointer<EVP_PKEY>` become `OpaquePointer` and without this code adjustment SwiftPM fails to build with `error: cannot find type 'EVP_PKEY' in scope`.

Modifications:
- Update dependency from 2.4.0 to 2.4.1
- Replace `Unsafe*Pointer<EVP_PKEY>` with `OpaquePointer`.