Deduplicate diagnostics in new --experimental-diagnostics-dedup mode
When compiling swift we're using many jobs to drive the compilation,
sometimes files are compiled not as primary file, but still emit
warnings or errors. This means that the same error/warning may be
emitted up to N times where N is the number of jobs or times a file is
included as non primary file in a compilation.

I've seen error duplication as high as 5 or 8 times.

This is a huge problem for:

- Humans reading the logs in command line, which includes CI outputs
  etc. because it seems like we have e.g. 25 errors, but we just have 5.
  - This is bad for experienced developers and CI systems just because
    of the amount of noise it introduces.
  - It is even worse for beginners of people evaluating Swift, emitting
    duplicate errors like this makes Swift seem unstable and "shocking"
    because so many errors are emitted for a trivial mistake, flooding
    terminal output visually.

- AI assistants because as they grep for error: they find N many more
  times outputs, each of those outputs can have multiple notes attached,
  which quickly burns through token counts.

Reproducer project: [HelloWorldApp.zip](https://github.com/user-attachments/files/25831256/HelloWorldApp.zip)
We have one error here in the project, however it is diagnosed as:

```
/private/tmp/HelloWorldApp/Sources/HelloWorldApp/UserStore.swift:3:51: error: extra argument 'lastName' in call
 1 | struct UserStore {
 2 |     private let users: [User] = [
 3 |         User(id: 1, firstName: "Alice", lastName: "Smith", email: "alice@example.com"),
   |                                                   `- error: extra argument 'lastName' in call
 4 |         // User(id: 2, firstName: "Bob", lastName: "Jones", email: "bob@example.com"),
 5 |         // User(id: 3, firstName: "Carol", lastName: "White", email: "carol@example.com"),
error: emit-module command failed with exit code 1 (use -v to see invocation)
/private/tmp/HelloWorldApp/Sources/HelloWorldApp/UserStore.swift:3:51: error: extra argument 'lastName' in call
 1 | struct UserStore {
 2 |     private let users: [User] = [
 3 |         User(id: 1, firstName: "Alice", lastName: "Smith", email: "alice@example.com"),
   |                                                   `- error: extra argument 'lastName' in call
 4 |         // User(id: 2, firstName: "Bob", lastName: "Jones", email: "bob@example.com"),
 5 |         // User(id: 3, firstName: "Carol", lastName: "White", email: "carol@example.com"),
/private/tmp/HelloWorldApp/Sources/HelloWorldApp/UserStore.swift:3:51: error: extra argument 'lastName' in call
 1 | struct UserStore {
 2 |     private let users: [User] = [
 3 |         User(id: 1, firstName: "Alice", lastName: "Smith", email: "alice@example.com"),
   |                                                   `- error: extra argument 'lastName' in call
 4 |         // User(id: 2, firstName: "Bob", lastName: "Jones", email: "bob@example.com"),
 5 |         // User(id: 3, firstName: "Carol", lastName: "White", email: "carol@example.com"),
/private/tmp/HelloWorldApp/Sources/HelloWorldApp/UserStore.swift:3:51: error: extra argument 'lastName' in call
 1 | struct UserStore {
 2 |     private let users: [User] = [
 3 |         User(id: 1, firstName: "Alice", lastName: "Smith", email: "alice@example.com"),
   |                                                   `- error: extra argument 'lastName' in call
 4 |         // User(id: 2, firstName: "Bob", lastName: "Jones", email: "bob@example.com"),
 5 |         // User(id: 3, firstName: "Carol", lastName: "White", email: "carol@example.com"),
```

which is the exact error, just repeated 4 times.

With this fix, we get exactly 1 error diagnostic.

We should also see if swift-frontend can try to deduplicate the errors a
little bit and I have some PoC of that as well, but it cannot do that
100% because we may still have multiple frontend tasks try to compile
the same file as secondary and cause the same error again, so I think we
must deduplicate this in swiftpm layer

I have initially discussed this with @bri and look forward to at least
landing it as experimental flag for the time being.

Introduce a new flag --experimental-diagnostics-dedup to enable this new
de-duplicating mode.

In this mode, we key each emitted diagnostic in the
LLBuildProgressTracker by its file/line/col and exact error message. If
an error message would be emitted twice, we do not emit it.

Removes duplicated diagnostics

Resolves rdar://84599581